#-------------------------------
# General Site Settings
title: Mongolian Data Stories
logo: # You can add own logo. For example '/images/logo.png'.
description: Telling Mongolia's story through data.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://mongoliandatastories.com" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  avatar: '/images/logo.png'
  name: Robert Ritz
  job: Telling Mongolia's story through data.

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/mongoliandatastories"}
- {icon: "ion-logo-facebook", link: "https://www.facebook.com/mongoliandatastories"}

# Example of adding a new link to the author section and footer - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Featured Slider
slider: true # NOTE - By default, the slider is set to display featured posts. To add featured post to the slider, add the field, featured: true in the YAML front matter block. If you do not want to use the slider, leave the slider field empty.


#-------------------------------
# Contact Settings
contact:
  email: robertritz@outlook.com # Add your email for contant form
  description: Contact Mongolian Data Stories. # Add a description of your form

# NOTE
# Bonso comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: true # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-text: Subscribe to our newsletter and weâ€™ll send you the emails of latest posts. # Add your description.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-feed

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed